language: node_js
node_js:
  - 12
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/cosysoft-11ty/"
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master